
HOSTUSER=${USER}

# mariadb
MARIA_DB_USER=root
MARIA_DB_PASS=${MARIA_ROOT_PASSWORD}
MARIA_DB_HOST=210.219.210.195
MARIA_DB_PORT=3306
MARIA_DB_HOST_PATH=$PWD/db/
MARIA_ROOT_PASSWORD=mobiustest

# mobius
MOBIUS_HOST=${MARIA_DB_HOST}
MOBIUS_HTTP_PORT=7579
MOBIUS_MQTT_PORT=1883
MOBIUS_NOTI_PORT=9727
MOBIUS_BASE=/home/tifler/work/iot/server/mobius-src/

# GTracker
GTRACKER_BASE=/home/tifler/work/iot/server/gtracker-server/anapass/
GTRACKER_SERVER_PORT=8080
GTRACKER_DB_USER=${MARIA_DB_USER}
GTRACKER_DB_PASS=${MARIA_DB_PASS}
GTRACKER_DB_HOST=${MARIA_DB_HOST}
GTRACKER_DB_PORT=${MARIA_DB_PORT}
