CREATE TABLE WPS (
    Id INT(11) AUTO_INCREMENT PRIMARY KEY,
    mac1 VARCHAR(20) NOT NULL,
    mac2 VARCHAR(20) NOT NULL,
    lat DOUBLE NOT NULL,
    lng DOUBLE NOT NULL,
    accuracy INT NOT NULL,
    timestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
